
	<div class="container top-carga">
		<div class="row">
			<div class="col-2">
			</div>
			<div class="col">				
				<div class="row">
					<div class="col-12 titulo-formulario tituloo font-weight-bold wow-outer linea">
						Registrarte
					</div>
					
					
					
					<div class="col-12 furmulario">	

							<div class="form-group row">
							  <label for="example-email-input" class="col-4 col-form-label">Email</label>
							  <div class="col-8  input-group-prepend">
							    <input class="form-control" type="email" value="" id="email" data-bandera='0'>

							  </div>
							  <div class="text-danger col-6 offset-md-4" id="error-email" ></div>
							  
							</div>
							<div class="form-group row">								
							  <label for="example-search-input" class="col-4 col-form-label">Contraseña</label>					
							  <div class="col input-group-prepend">
							    <input class="form-control" type="password" value="" id="clave1" data-bandera='0'>
							  </div>
							  <div class="text-danger col-6 offset-md-4 " id="error-clave1" ></div>
							</div>
							<div class="form-group row">			
							  <label for="example-search-input" class="col-4 col-form-label">Confirmar Contraseña</label>					
							  <div class="col input-group-prepend">
							    <input class="form-control" type="password" value="" id="clave2" data-bandera='0'>
							  </div>
							  <div class="text-danger col-6 offset-md-4" id="error-clave2" ></div>
							</div>							
							<div class="col-12 wow-outer">
          					 <center> <a class="button button-primary button-winona button-md" href="#" id="enviar_registro">
          					    <div class="content-original">
          					      Registrate
          					    </div>
          					    <div class="content-dubbed">
          					      Registrate
          					    </div>
          					  </a></center>
          					</div>
						</div>
					</div>
			</div>
			<div class="col-2">
			</div>
		</div>
	</div>
