
<div class="container-fluid cambio" data-aos="fade" data-aos-delay="500">
  <div class="row justify-content-center">
    <div class="col-8">
      <h3 class="text-center">Cambio de contraceña</h3>
    </div>
    <div class="col-8">
      
        <div class="input-group mb-3">
          <font class="col-2 align-items-center">clave actual</font>
          <div class=" input-group-prepend">
            <span class="input-group-text icon-lock" id="basic-addon1">
             
            </span>
          </div>
          <input  class="form-control" placeholder="clave actual" aria-describedby="basic-addon1" type="password" id="actual" name="actual" required="required">
        </div>

        <div class="input-group mb-3">
          <font class="col-2 align-items-center">clave nueva</font>
          <div class="input-group-prepend">
            <span class="input-group-text icon-lock" id="basic-addon1">
             
            </span>
          </div>
          <input  class="form-control" placeholder="clave nueva" aria-describedby="basic-addon1" type="password" id="nueva" name="nueva" required="required">
        </div>

        <div class="input-group mb-3">
          <font class="col-2 align-items-center">repita clave</font>
          <div class="input-group-prepend">
            <span class="input-group-text icon-lock" id="basic-addon1">
             
            </span>
          </div>
          <input  class="form-control" placeholder="repita clave" aria-describedby="basic-addon1" type="password" id="confirmar" name="confirmar" required="required">
        </div>

        <div class="input-group mb-3 justify-content-around">
            <button id="cambiarclave" type="button" class="btn btn-primary btn-md col-4">CAMBIAR CLAVE</button>
            <button onclick="javascript:history.back()" class="btn btn-primary btn-md col-4">CANCELAR</button>
          
        </div>


    </div>
  </div>
</div>

        


