<div class=""  data-aos="fade">
    <div class="container-fluid">
      
      <div class="row justify-content-center">
        <div class="col-md-7">
          <div class="row mb-5 site-section">
            <div class="col-12 ">
              <h2 class="site-section-heading text-center">Conocenos</h2>
            </div>
          </div>

          <div class="row mb-5">
            <div class="col-md-7">
              <img src="<?php echo BASE_URL; ?>public/img/images/gerbera_conocenos.jpg" alt="Images" class="img-fluid">
            </div>
            <div class="col-md-4 ml-auto">
              <h3>Gerbera</h3>
              <p>Somos una florería a domicilio con una amplia experiencia.
                  Trabajamos variedad de flores naturales sujetas a la temporada de estas. 
                  Disponemos desde arreglos clásicos hasta matrimonio completos.</p>
            </div>
          </div>
        </div>    
      </div>
    </div>
  </div>