
<div class="container"> 
  <div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm login-py">
      <p id="error-login" class="text-danger">
        <?php echo $retVal = (isset($this->_error)) ? $this->_error : '' ; ; ?>
      </p>
      
      
      

      

     <div id="name"></div>


      <form class="" id="form-login" role="form" method="post" action="<?php echo BASE_URL?>login">
      <input type="hidden" value="1" name="enviar" />
      
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">
            <i class="fa fa-user" aria-hidden="true"></i>
          </span>
        </div>
        <input type="text" name="usuario" class="form-control" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>" placeholder="Usuario" aria-label="Username" aria-describedby="basic-addon1">
      </div>

       <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">
            <i class="fa fa-unlock-alt" aria-hidden="true"></i>
          </span>
        </div>
        <input type="password" name="pass" class="form-control"  placeholder="Contraseña" aria-label="password" aria-describedby="basic-addon1">
      </div>

        <div class="boton-login">
        <a id="enviar" class="button button-primary button-winona button-md" href="#">
          <div class="content-original">
            <div class="content-original">
               INICIAR SESIÓN
            </div>
            <div class="content-dubbed">
              INICIAR SESIÓN
            </div>
          </div>
          <div class="content-dubbed">
            <div class="content-original">
              INICIAR SESIÓN
            </div>
          <div class="content-dubbed">
              INICIAR SESIÓN
          </div>
        </div>
      </a>
      </div>
      </form>
      <div class="conte-boton-google">
        
        <div id="gSignInWrapper">
         
         <div id="customBtn" class="btn btn-primary btn-lg">
          <div class="g-logo">
            <img class="g-img" src="https://img.icons8.com/color/48/000000/google-logo.png">
          </div>
          <div class="g-letras">
               Google
          </div>
          </div>
      </div>
      </div>
      <div class="conte-boton-facebook" id="login-facebook">
        
        <div id="gSignInWrapper">
         
         <div id="customBtn" class="btn btn-primary btn-lg">
          <div class="g-logo">
            <img class="g-img" src="https://img.icons8.com/color/48/000000/facebook.png">
          </div>
          <div class="f-letras">
               Facebook
          </div>
          </div>
      </div>
      </div>
      <label for="example-search-input" class="col-12 col-form-label"><center><a href="<?php echo BASE_URL?>registro">Registrate</a></center></label>
    </div>
    <div class="col-sm">
      
    </div>
  </div>
</div>
