
<div class="container"> 
  <div class="row justify-content-center">
   
    <div class="col-4  login-py">
      <p id="error-login" class="text-danger">
        <?php echo $retVal = (isset($this->_error)) ? $this->_error : '' ; ; ?>
      </p>
      <h4 class="site-section-heading text-center">Login</h4>
      
      <div class="imagen-log col-12">

        <img class="img muneco" src="<?php echo BASE_URL ?>/public/img/profile/usuario_out.jpg">
        
      </div>

      

     <div id="name"></div>


      <form class="" id="form-login" role="form" method="post" action="<?php echo BASE_URL?>login">
      <input type="hidden" value="1" name="enviar" />
      
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">
            <i class="icon-user" aria-hidden="true"></i>
          </span>
        </div>
        <input type="text" name="usuario" class="form-control" value="<?php if(isset($this->datos)) echo $this->datos['usuario']; ?>" placeholder="Usuario" aria-label="Username" aria-describedby="basic-addon1">
      </div>

       <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="basic-addon1">
            <i class=" icon-lock" aria-hidden="true"></i>
          </span>
        </div>
        <input type="password" name="pass" class="form-control"  placeholder="Contraseña" aria-label="password" aria-describedby="basic-addon1">
      </div>

       <button type="submit" class="btn btn-primary col-12" >enviar</button>
      </form>

   
      
    </div>
   
  </div>
</div>
