<div class="container-fluid" data-aos="fade" data-aos-delay="500">

  <h2 class="mb-3 text-center">Publicar nuevo contenido</h2>
  <div class="row justify-content-center">

    <form class="col-8">
      <div class="form-group">
        <label for="titulo">Titulo</label>
        <input type="text" class="form-control" id="titulo" aria-describedby="titulo" placeholder="Titulo de la publicacion">
        <small id="titulo" class="form-text text-muted">Inserte un titulo para la nueva publicacion</small>
      </div>
      <div class="form-group">
        <label for="descrip">Descripcion</label>
        <textarea class="form-control" id="descrip" aria-describedby="descrip" placeholder="Descripcion"></textarea>
        <small id="descrip" class="form-text text-muted">Descripcion de la publicacion.</small>
      </div>
      <div class="form-group">
        <label for="categ">Categoria</label>
        <select type="text" class="form-control" id="categ" aria-describedby="categ" placeholder="">
          <option value="">1</option>
          <option value="">2</option>
          <option value="">3</option>
        </select>
        <small id="categ" class="form-text text-muted">seleccione la categoria donde se visualizara la publicacion.</small>
      </div>
      <div id='carga-img' class="dropzone"></div>  
      <div class="row form-group">
            <div class="col-md-12">
                  <input type="button" id="btn_enviar"  value="Enviar" class="btn btn-primary py-2 px-4 text-white">
                    
            </div>
      </div>
      

    </form>
  </div>    
  

</div>