

   

  <div class="container-fluid" data-aos="fade" data-aos-delay="500">
    <div class="swiper-container images-carousel">
        <div class="swiper-wrapper">

       

          <?php for ($i=0; $i < count($this->_seccion) ; $i++): ?>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3"><?php echo $this->_seccion[$i]['titulo'];  ?></h2>
                  <a href="<?php echo BASE_URL; ?>galeria/index/<?php echo $this->_seccion[$i]['titulo']; ?>" class="btn btn-outline-white py-2 px-4">Mas Fotos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/<?php echo $this->_seccion[$i]['foto']; ?>" alt="Image">
              </div>
            </div>
          <?php endfor; ?>


           
        </div>

        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
  </div>



    

    
    
  </div>