

   

  <div class="container-fluid" data-aos="fade" data-aos-delay="500">
    <div class="swiper-container images-carousel">
        <div class="swiper-wrapper">
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Nature</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_1.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Portrait</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_2.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">People</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_3.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Architecture</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_4.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Animals</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_5.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Sports</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_6.jpg" alt="Image">
              </div>
            </div>
            <div class="swiper-slide">
              <div class="image-wrap">
                <div class="image-info">
                  <h2 class="mb-3">Travel</h2>
                  <a href="single.html" class="btn btn-outline-white py-2 px-4">More Photos</a>
                </div>
                <img src="<?php echo BASE_URL; ?>public/img/images/img_7.jpg" alt="Image">
              </div>
            </div>
        </div>

        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
        <div class="swiper-scrollbar"></div>
    </div>
  </div>

  <div class="footer py-4">
    <div class="container-fluid">
      <p>
      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      Copyright &copy;<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
      <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </p>
    </div>
  </div>

    

    
    
  </div>